# Generated by Django 3.0.5 on 2020-04-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'faculty'), ('staff', 'Staff'), ('other', 'Other')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(choices=[('Pomona', 'Pomona'), ('Pitzer', 'Pitzer'), ('Claremont McKenna', 'Claremont McKenna'), ('Harvey Mudd', 'Harvey Mudd'), ('Scripps', 'Scripps')], default='PO', max_length=20),
        ),
    ]
