# Generated by Django 3.0.5 on 2020-05-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dininghall',
            options={'managed': False},
        ),
    ]
