# Generated by Django 3.0.5 on 2020-05-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200501_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dininghall',
            options={'managed': True},
        ),
    ]
