# Generated by Django 3.0.5 on 2020-05-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200501_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dininghall',
            options={'managed': False},
        ),
    ]
