# Generated by Django 3.0.5 on 2020-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningHall',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=20)),
            ],
        ),
    ]
