# Generated by Django 3.0.5 on 2020-04-08 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200408_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='hours',
        ),
        migrations.AddField(
            model_name='meal',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
