# Generated by Django 3.0.5 on 2020-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200408_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
