# Generated by Django 3.0.5 on 2020-04-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200408_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
