# Generated by Django 3.0.5 on 2020-04-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20200408_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='meal',
            field=models.ForeignKey(db_column='meal', on_delete=django.db.models.deletion.CASCADE, to='hello.Meal'),
        ),
    ]
