# Generated by Django 3.0.5 on 2020-04-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20200408_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Meal'),
        ),
    ]
