# Generated by Django 3.0.5 on 2020-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200408_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
