# Generated by Django 3.0.5 on 2020-04-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20200408_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrestrictions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
