# Generated by Django 3.0.5 on 2020-04-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20200408_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietaryrestrictionsofdish',
            old_name='dietary_restriction',
            new_name='dietary_restrictio',
        ),
    ]
