# Generated by Django 3.0.5 on 2020-04-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20200408_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrestrictionsofdish',
            name='dietary_restriction',
        ),
    ]
