# Generated by Django 3.0.5 on 2020-04-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_dietaryrestrictionsofdish_dietary_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrestrictionsofdish',
            name='dietary_restriction',
        ),
    ]
