# Generated by Django 3.0.5 on 2020-04-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_remove_dietaryrestrictionsofdish_dietary_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrestrictionsofdish',
            name='dietary_restriction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.DietaryRestrictions'),
            preserve_default=False,
        ),
    ]
