# Generated by Django 3.0.5 on 2020-04-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_dietaryrestrictionsofdish_dietary_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
