# Generated by Django 3.0.5 on 2020-04-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_auto_20200408_2214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutritionfactsofdish',
            unique_together={('dish', 'nutrition_fact')},
        ),
    ]
