# Generated by Django 3.0.5 on 2020-04-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_auto_20200408_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dining_hall',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.DiningHall'),
            preserve_default=False,
        ),
    ]
