# Generated by Django 3.0.5 on 2020-04-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0027_auto_20200410_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='dining_hal',
            new_name='dining_hall',
        ),
    ]
