# Generated by Django 3.0.5 on 2020-04-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_auto_20200410_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dining_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.DiningHall'),
        ),
    ]
