# Generated by Django 3.0.5 on 2020-04-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_auto_20200410_2129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('dish', 'meal')},
        ),
    ]
